// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DebugArgs {}

impl From<DebugArgs> for super::Reducer {
    fn from(args: DebugArgs) -> Self {
        Self::Debug
    }
}

impl __sdk::InModule for DebugArgs {
    type Module = super::RemoteModule;
}

pub struct DebugCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `debug`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait debug {
    /// Request that the remote module invoke the reducer `debug` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_debug`] callbacks.
    fn debug(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `debug`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DebugCallbackId`] can be passed to [`Self::remove_on_debug`]
    /// to cancel the callback.
    fn on_debug(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DebugCallbackId;
    /// Cancel a callback previously registered by [`Self::on_debug`],
    /// causing it not to run in the future.
    fn remove_on_debug(&self, callback: DebugCallbackId);
}

impl debug for super::RemoteReducers {
    fn debug(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("debug", DebugArgs {})
    }
    fn on_debug(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DebugCallbackId {
        DebugCallbackId(self.imp.on_reducer(
            "debug",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Debug {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_debug(&self, callback: DebugCallbackId) {
        self.imp.remove_on_reducer("debug", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `debug`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_debug {
    /// Set the call-reducer flags for the reducer `debug` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn debug(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_debug for super::SetReducerFlags {
    fn debug(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("debug", flags);
    }
}
