// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::client_type::Client;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `logged_out_client`.
///
/// Obtain a handle from the [`LoggedOutClientTableAccess::logged_out_client`] method on [`super::RemoteTables`],
/// like `ctx.db.logged_out_client()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.logged_out_client().on_insert(...)`.
pub struct LoggedOutClientTableHandle<'ctx> {
    imp: __sdk::TableHandle<Client>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `logged_out_client`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LoggedOutClientTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LoggedOutClientTableHandle`], which mediates access to the table `logged_out_client`.
    fn logged_out_client(&self) -> LoggedOutClientTableHandle<'_>;
}

impl LoggedOutClientTableAccess for super::RemoteTables {
    fn logged_out_client(&self) -> LoggedOutClientTableHandle<'_> {
        LoggedOutClientTableHandle {
            imp: self.imp.get_table::<Client>("logged_out_client"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LoggedOutClientInsertCallbackId(__sdk::CallbackId);
pub struct LoggedOutClientDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LoggedOutClientTableHandle<'ctx> {
    type Row = Client;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Client> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LoggedOutClientInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoggedOutClientInsertCallbackId {
        LoggedOutClientInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LoggedOutClientInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LoggedOutClientDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LoggedOutClientDeleteCallbackId {
        LoggedOutClientDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LoggedOutClientDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Client>("logged_out_client");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct LoggedOutClientUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LoggedOutClientTableHandle<'ctx> {
    type UpdateCallbackId = LoggedOutClientUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LoggedOutClientUpdateCallbackId {
        LoggedOutClientUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LoggedOutClientUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Client>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Client>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `logged_out_client`,
/// which allows point queries on the field of the same name
/// via the [`LoggedOutClientIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.logged_out_client().id().find(...)`.
pub struct LoggedOutClientIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Client, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LoggedOutClientTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `logged_out_client`.
    pub fn id(&self) -> LoggedOutClientIdUnique<'ctx> {
        LoggedOutClientIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LoggedOutClientIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Client> {
        self.imp.find(col_val)
    }
}
