// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerViewport {
    pub id: __sdk::Identity,
    pub tl_x: i64,
    pub tl_y: i64,
    pub br_x: i64,
    pub br_y: i64,
}

impl __sdk::InModule for PlayerViewport {
    type Module = super::RemoteModule;
}
