// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetPlayerViewportArgs {
    pub x: i64,
    pub y: i64,
    pub size: i64,
    pub margin: i64,
}

impl From<SetPlayerViewportArgs> for super::Reducer {
    fn from(args: SetPlayerViewportArgs) -> Self {
        Self::SetPlayerViewport {
            x: args.x,
            y: args.y,
            size: args.size,
            margin: args.margin,
        }
    }
}

impl __sdk::InModule for SetPlayerViewportArgs {
    type Module = super::RemoteModule;
}

pub struct SetPlayerViewportCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_player_viewport`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_player_viewport {
    /// Request that the remote module invoke the reducer `set_player_viewport` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_player_viewport`] callbacks.
    fn set_player_viewport(&self, x: i64, y: i64, size: i64, margin: i64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_player_viewport`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetPlayerViewportCallbackId`] can be passed to [`Self::remove_on_set_player_viewport`]
    /// to cancel the callback.
    fn on_set_player_viewport(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i64, &i64, &i64, &i64) + Send + 'static,
    ) -> SetPlayerViewportCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_player_viewport`],
    /// causing it not to run in the future.
    fn remove_on_set_player_viewport(&self, callback: SetPlayerViewportCallbackId);
}

impl set_player_viewport for super::RemoteReducers {
    fn set_player_viewport(&self, x: i64, y: i64, size: i64, margin: i64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "set_player_viewport",
            SetPlayerViewportArgs { x, y, size, margin },
        )
    }
    fn on_set_player_viewport(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i64, &i64, &i64, &i64) + Send + 'static,
    ) -> SetPlayerViewportCallbackId {
        SetPlayerViewportCallbackId(self.imp.on_reducer(
            "set_player_viewport",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetPlayerViewport { x, y, size, margin },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, x, y, size, margin)
            }),
        ))
    }
    fn remove_on_set_player_viewport(&self, callback: SetPlayerViewportCallbackId) {
        self.imp
            .remove_on_reducer("set_player_viewport", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_player_viewport`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_player_viewport {
    /// Set the call-reducer flags for the reducer `set_player_viewport` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_player_viewport(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_player_viewport for super::SetReducerFlags {
    fn set_player_viewport(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("set_player_viewport", flags);
    }
}
