// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sage_fleet_pos_type::SageFleetPos;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFleetPosArgs {
    pub pos: SageFleetPos,
}

impl From<UpdateFleetPosArgs> for super::Reducer {
    fn from(args: UpdateFleetPosArgs) -> Self {
        Self::UpdateFleetPos { pos: args.pos }
    }
}

impl __sdk::InModule for UpdateFleetPosArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateFleetPosCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_fleet_pos`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_fleet_pos {
    /// Request that the remote module invoke the reducer `update_fleet_pos` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_fleet_pos`] callbacks.
    fn update_fleet_pos(&self, pos: SageFleetPos) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_fleet_pos`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateFleetPosCallbackId`] can be passed to [`Self::remove_on_update_fleet_pos`]
    /// to cancel the callback.
    fn on_update_fleet_pos(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SageFleetPos) + Send + 'static,
    ) -> UpdateFleetPosCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_fleet_pos`],
    /// causing it not to run in the future.
    fn remove_on_update_fleet_pos(&self, callback: UpdateFleetPosCallbackId);
}

impl update_fleet_pos for super::RemoteReducers {
    fn update_fleet_pos(&self, pos: SageFleetPos) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_fleet_pos", UpdateFleetPosArgs { pos })
    }
    fn on_update_fleet_pos(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SageFleetPos) + Send + 'static,
    ) -> UpdateFleetPosCallbackId {
        UpdateFleetPosCallbackId(self.imp.on_reducer(
            "update_fleet_pos",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateFleetPos { pos },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, pos)
            }),
        ))
    }
    fn remove_on_update_fleet_pos(&self, callback: UpdateFleetPosCallbackId) {
        self.imp.remove_on_reducer("update_fleet_pos", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_fleet_pos`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_fleet_pos {
    /// Set the call-reducer flags for the reducer `update_fleet_pos` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_fleet_pos(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_fleet_pos for super::SetReducerFlags {
    fn update_fleet_pos(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_fleet_pos", flags);
    }
}
