// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sage_star_type::SageStar;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateStarArgs {
    pub star: SageStar,
}

impl From<UpdateStarArgs> for super::Reducer {
    fn from(args: UpdateStarArgs) -> Self {
        Self::UpdateStar { star: args.star }
    }
}

impl __sdk::InModule for UpdateStarArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateStarCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_star`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_star {
    /// Request that the remote module invoke the reducer `update_star` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_star`] callbacks.
    fn update_star(&self, star: SageStar) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_star`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateStarCallbackId`] can be passed to [`Self::remove_on_update_star`]
    /// to cancel the callback.
    fn on_update_star(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SageStar) + Send + 'static,
    ) -> UpdateStarCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_star`],
    /// causing it not to run in the future.
    fn remove_on_update_star(&self, callback: UpdateStarCallbackId);
}

impl update_star for super::RemoteReducers {
    fn update_star(&self, star: SageStar) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_star", UpdateStarArgs { star })
    }
    fn on_update_star(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SageStar) + Send + 'static,
    ) -> UpdateStarCallbackId {
        UpdateStarCallbackId(self.imp.on_reducer(
            "update_star",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateStar { star },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, star)
            }),
        ))
    }
    fn remove_on_update_star(&self, callback: UpdateStarCallbackId) {
        self.imp.remove_on_reducer("update_star", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_star`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_star {
    /// Set the call-reducer flags for the reducer `update_star` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_star(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_star for super::SetReducerFlags {
    fn update_star(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_star", flags);
    }
}
