[package]
name = "staratlas-starbased-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang.workspace = true
litesvm.workspace = true
solana-sdk.workspace = true
staratlas-player-profile.workspace = true
staratlas-sage.workspace = true