// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sage_fleet_warping_type::SageFleetWarping;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fleet_warping`.
///
/// Obtain a handle from the [`FleetWarpingTableAccess::fleet_warping`] method on [`super::RemoteTables`],
/// like `ctx.db.fleet_warping()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_warping().on_insert(...)`.
pub struct FleetWarpingTableHandle<'ctx> {
    imp: __sdk::TableHandle<SageFleetWarping>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fleet_warping`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FleetWarpingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FleetWarpingTableHandle`], which mediates access to the table `fleet_warping`.
    fn fleet_warping(&self) -> FleetWarpingTableHandle<'_>;
}

impl FleetWarpingTableAccess for super::RemoteTables {
    fn fleet_warping(&self) -> FleetWarpingTableHandle<'_> {
        FleetWarpingTableHandle {
            imp: self.imp.get_table::<SageFleetWarping>("fleet_warping"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FleetWarpingInsertCallbackId(__sdk::CallbackId);
pub struct FleetWarpingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FleetWarpingTableHandle<'ctx> {
    type Row = SageFleetWarping;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SageFleetWarping> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FleetWarpingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetWarpingInsertCallbackId {
        FleetWarpingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetWarpingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FleetWarpingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetWarpingDeleteCallbackId {
        FleetWarpingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetWarpingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SageFleetWarping>("fleet_warping");
    _table.add_unique_constraint::<String>("pubkey", |row| &row.pubkey);
}
pub struct FleetWarpingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FleetWarpingTableHandle<'ctx> {
    type UpdateCallbackId = FleetWarpingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FleetWarpingUpdateCallbackId {
        FleetWarpingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FleetWarpingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SageFleetWarping>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SageFleetWarping>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `pubkey` unique index on the table `fleet_warping`,
/// which allows point queries on the field of the same name
/// via the [`FleetWarpingPubkeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_warping().pubkey().find(...)`.
pub struct FleetWarpingPubkeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SageFleetWarping, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FleetWarpingTableHandle<'ctx> {
    /// Get a handle on the `pubkey` unique index on the table `fleet_warping`.
    pub fn pubkey(&self) -> FleetWarpingPubkeyUnique<'ctx> {
        FleetWarpingPubkeyUnique {
            imp: self.imp.get_unique_constraint::<String>("pubkey"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FleetWarpingPubkeyUnique<'ctx> {
    /// Find the subscribed row whose `pubkey` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SageFleetWarping> {
        self.imp.find(col_val)
    }
}
