// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::idle_type::Idle;
use super::move_subwarp_type::MoveSubwarp;
use super::move_warp_type::MoveWarp;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum FleetState {
    Idle(Idle),

    MoveWarp(MoveWarp),

    MoveSubwarp(MoveSubwarp),
}

impl __sdk::InModule for FleetState {
    type Module = super::RemoteModule;
}
