// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sage_fleet_type::SageFleet;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fleet`.
///
/// Obtain a handle from the [`FleetTableAccess::fleet`] method on [`super::RemoteTables`],
/// like `ctx.db.fleet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet().on_insert(...)`.
pub struct FleetTableHandle<'ctx> {
    imp: __sdk::TableHandle<SageFleet>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fleet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FleetTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FleetTableHandle`], which mediates access to the table `fleet`.
    fn fleet(&self) -> FleetTableHandle<'_>;
}

impl FleetTableAccess for super::RemoteTables {
    fn fleet(&self) -> FleetTableHandle<'_> {
        FleetTableHandle {
            imp: self.imp.get_table::<SageFleet>("fleet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FleetInsertCallbackId(__sdk::CallbackId);
pub struct FleetDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FleetTableHandle<'ctx> {
    type Row = SageFleet;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SageFleet> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FleetInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetInsertCallbackId {
        FleetInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FleetDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetDeleteCallbackId {
        FleetDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SageFleet>("fleet");
    _table.add_unique_constraint::<String>("pubkey", |row| &row.pubkey);
}
pub struct FleetUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FleetTableHandle<'ctx> {
    type UpdateCallbackId = FleetUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FleetUpdateCallbackId {
        FleetUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FleetUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SageFleet>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SageFleet>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `pubkey` unique index on the table `fleet`,
/// which allows point queries on the field of the same name
/// via the [`FleetPubkeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet().pubkey().find(...)`.
pub struct FleetPubkeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SageFleet, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FleetTableHandle<'ctx> {
    /// Get a handle on the `pubkey` unique index on the table `fleet`.
    pub fn pubkey(&self) -> FleetPubkeyUnique<'ctx> {
        FleetPubkeyUnique {
            imp: self.imp.get_unique_constraint::<String>("pubkey"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FleetPubkeyUnique<'ctx> {
    /// Find the subscribed row whose `pubkey` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SageFleet> {
        self.imp.find(col_val)
    }
}
