// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_viewport_type::PlayerViewport;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_viewport`.
///
/// Obtain a handle from the [`PlayerViewportTableAccess::player_viewport`] method on [`super::RemoteTables`],
/// like `ctx.db.player_viewport()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_viewport().on_insert(...)`.
pub struct PlayerViewportTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerViewport>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_viewport`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerViewportTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerViewportTableHandle`], which mediates access to the table `player_viewport`.
    fn player_viewport(&self) -> PlayerViewportTableHandle<'_>;
}

impl PlayerViewportTableAccess for super::RemoteTables {
    fn player_viewport(&self) -> PlayerViewportTableHandle<'_> {
        PlayerViewportTableHandle {
            imp: self.imp.get_table::<PlayerViewport>("player_viewport"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerViewportInsertCallbackId(__sdk::CallbackId);
pub struct PlayerViewportDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerViewportTableHandle<'ctx> {
    type Row = PlayerViewport;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerViewport> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerViewportInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerViewportInsertCallbackId {
        PlayerViewportInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerViewportInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerViewportDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerViewportDeleteCallbackId {
        PlayerViewportDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerViewportDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerViewport>("player_viewport");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct PlayerViewportUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerViewportTableHandle<'ctx> {
    type UpdateCallbackId = PlayerViewportUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerViewportUpdateCallbackId {
        PlayerViewportUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerViewportUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerViewport>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerViewport>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `player_viewport`,
/// which allows point queries on the field of the same name
/// via the [`PlayerViewportIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_viewport().id().find(...)`.
pub struct PlayerViewportIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerViewport, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerViewportTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `player_viewport`.
    pub fn id(&self) -> PlayerViewportIdUnique<'ctx> {
        PlayerViewportIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerViewportIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerViewport> {
        self.imp.find(col_val)
    }
}
