// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateConfigSlotArgs {
    pub slot: u64,
}

impl From<UpdateConfigSlotArgs> for super::Reducer {
    fn from(args: UpdateConfigSlotArgs) -> Self {
        Self::UpdateConfigSlot { slot: args.slot }
    }
}

impl __sdk::InModule for UpdateConfigSlotArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateConfigSlotCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_config_slot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_config_slot {
    /// Request that the remote module invoke the reducer `update_config_slot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_config_slot`] callbacks.
    fn update_config_slot(&self, slot: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_config_slot`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateConfigSlotCallbackId`] can be passed to [`Self::remove_on_update_config_slot`]
    /// to cancel the callback.
    fn on_update_config_slot(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> UpdateConfigSlotCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_config_slot`],
    /// causing it not to run in the future.
    fn remove_on_update_config_slot(&self, callback: UpdateConfigSlotCallbackId);
}

impl update_config_slot for super::RemoteReducers {
    fn update_config_slot(&self, slot: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_config_slot", UpdateConfigSlotArgs { slot })
    }
    fn on_update_config_slot(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> UpdateConfigSlotCallbackId {
        UpdateConfigSlotCallbackId(self.imp.on_reducer(
            "update_config_slot",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateConfigSlot { slot },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, slot)
            }),
        ))
    }
    fn remove_on_update_config_slot(&self, callback: UpdateConfigSlotCallbackId) {
        self.imp.remove_on_reducer("update_config_slot", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_config_slot`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_config_slot {
    /// Set the call-reducer flags for the reducer `update_config_slot` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_config_slot(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_config_slot for super::SetReducerFlags {
    fn update_config_slot(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_config_slot", flags);
    }
}
