[package]
name = "common-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
solana-client = { workspace = true }
solana-sdk = { workspace = true }
sqlx = { workspace = true }
