// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::client_type::Client;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `client`.
///
/// Obtain a handle from the [`ClientTableAccess::client`] method on [`super::RemoteTables`],
/// like `ctx.db.client()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.client().on_insert(...)`.
pub struct ClientTableHandle<'ctx> {
    imp: __sdk::TableHandle<Client>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `client`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClientTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClientTableHandle`], which mediates access to the table `client`.
    fn client(&self) -> ClientTableHandle<'_>;
}

impl ClientTableAccess for super::RemoteTables {
    fn client(&self) -> ClientTableHandle<'_> {
        ClientTableHandle {
            imp: self.imp.get_table::<Client>("client"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClientInsertCallbackId(__sdk::CallbackId);
pub struct ClientDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClientTableHandle<'ctx> {
    type Row = Client;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Client> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClientInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClientInsertCallbackId {
        ClientInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClientInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClientDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClientDeleteCallbackId {
        ClientDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClientDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Client>("client");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}
pub struct ClientUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClientTableHandle<'ctx> {
    type UpdateCallbackId = ClientUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClientUpdateCallbackId {
        ClientUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClientUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Client>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Client>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `client`,
/// which allows point queries on the field of the same name
/// via the [`ClientIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.client().id().find(...)`.
pub struct ClientIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Client, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClientTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `client`.
    pub fn id(&self) -> ClientIdUnique<'ctx> {
        ClientIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClientIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Client> {
        self.imp.find(col_val)
    }
}
