// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sage_fleet_pos_type::SageFleetPos;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fleet_pos`.
///
/// Obtain a handle from the [`FleetPosTableAccess::fleet_pos`] method on [`super::RemoteTables`],
/// like `ctx.db.fleet_pos()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_pos().on_insert(...)`.
pub struct FleetPosTableHandle<'ctx> {
    imp: __sdk::TableHandle<SageFleetPos>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fleet_pos`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FleetPosTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FleetPosTableHandle`], which mediates access to the table `fleet_pos`.
    fn fleet_pos(&self) -> FleetPosTableHandle<'_>;
}

impl FleetPosTableAccess for super::RemoteTables {
    fn fleet_pos(&self) -> FleetPosTableHandle<'_> {
        FleetPosTableHandle {
            imp: self.imp.get_table::<SageFleetPos>("fleet_pos"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FleetPosInsertCallbackId(__sdk::CallbackId);
pub struct FleetPosDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FleetPosTableHandle<'ctx> {
    type Row = SageFleetPos;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SageFleetPos> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FleetPosInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetPosInsertCallbackId {
        FleetPosInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetPosInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FleetPosDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetPosDeleteCallbackId {
        FleetPosDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetPosDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SageFleetPos>("fleet_pos");
    _table.add_unique_constraint::<String>("pubkey", |row| &row.pubkey);
}
pub struct FleetPosUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FleetPosTableHandle<'ctx> {
    type UpdateCallbackId = FleetPosUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FleetPosUpdateCallbackId {
        FleetPosUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FleetPosUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SageFleetPos>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SageFleetPos>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `pubkey` unique index on the table `fleet_pos`,
/// which allows point queries on the field of the same name
/// via the [`FleetPosPubkeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_pos().pubkey().find(...)`.
pub struct FleetPosPubkeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SageFleetPos, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FleetPosTableHandle<'ctx> {
    /// Get a handle on the `pubkey` unique index on the table `fleet_pos`.
    pub fn pubkey(&self) -> FleetPosPubkeyUnique<'ctx> {
        FleetPosPubkeyUnique {
            imp: self.imp.get_unique_constraint::<String>("pubkey"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FleetPosPubkeyUnique<'ctx> {
    /// Find the subscribed row whose `pubkey` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SageFleetPos> {
        self.imp.find(col_val)
    }
}
