// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sage_fleet_type::SageFleet;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFleetArgs {
    pub fleet: SageFleet,
}

impl From<UpdateFleetArgs> for super::Reducer {
    fn from(args: UpdateFleetArgs) -> Self {
        Self::UpdateFleet { fleet: args.fleet }
    }
}

impl __sdk::InModule for UpdateFleetArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateFleetCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_fleet`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_fleet {
    /// Request that the remote module invoke the reducer `update_fleet` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_fleet`] callbacks.
    fn update_fleet(&self, fleet: SageFleet) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_fleet`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateFleetCallbackId`] can be passed to [`Self::remove_on_update_fleet`]
    /// to cancel the callback.
    fn on_update_fleet(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SageFleet) + Send + 'static,
    ) -> UpdateFleetCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_fleet`],
    /// causing it not to run in the future.
    fn remove_on_update_fleet(&self, callback: UpdateFleetCallbackId);
}

impl update_fleet for super::RemoteReducers {
    fn update_fleet(&self, fleet: SageFleet) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_fleet", UpdateFleetArgs { fleet })
    }
    fn on_update_fleet(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SageFleet) + Send + 'static,
    ) -> UpdateFleetCallbackId {
        UpdateFleetCallbackId(self.imp.on_reducer(
            "update_fleet",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateFleet { fleet },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, fleet)
            }),
        ))
    }
    fn remove_on_update_fleet(&self, callback: UpdateFleetCallbackId) {
        self.imp.remove_on_reducer("update_fleet", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_fleet`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_fleet {
    /// Set the call-reducer flags for the reducer `update_fleet` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_fleet(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_fleet for super::SetReducerFlags {
    fn update_fleet(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_fleet", flags);
    }
}
